// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-tfg3sPQTu4QB9C1e1MjEgGnb_QxSl8',
    appId: '1:290285572953:web:a66cabcf9a212396f13248',
    messagingSenderId: '290285572953',
    projectId: 'fir-de70a',
    authDomain: 'fir-de70a.firebaseapp.com',
    storageBucket: 'fir-de70a.firebasestorage.app',
    measurementId: 'G-9NQFNRZ4CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJK5c6gUhNLHfA_iDvKve0vtXrGMNDylI',
    appId: '1:290285572953:android:951c3494ef4b2185f13248',
    messagingSenderId: '290285572953',
    projectId: 'fir-de70a',
    storageBucket: 'fir-de70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJ3BxEbUMD7jGFNfd9gRPu4T65CQAa2c',
    appId: '1:290285572953:ios:d915d6121c0a7475f13248',
    messagingSenderId: '290285572953',
    projectId: 'fir-de70a',
    storageBucket: 'fir-de70a.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJ3BxEbUMD7jGFNfd9gRPu4T65CQAa2c',
    appId: '1:290285572953:ios:d915d6121c0a7475f13248',
    messagingSenderId: '290285572953',
    projectId: 'fir-de70a',
    storageBucket: 'fir-de70a.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2-tfg3sPQTu4QB9C1e1MjEgGnb_QxSl8',
    appId: '1:290285572953:web:6fd189cb9dade3bbf13248',
    messagingSenderId: '290285572953',
    projectId: 'fir-de70a',
    authDomain: 'fir-de70a.firebaseapp.com',
    storageBucket: 'fir-de70a.firebasestorage.app',
    measurementId: 'G-6NGX81VWX3',
  );
}
